# Site settings
author: Seth Todd
title: Some Guy Learning to Code
header-img: img/home-bg.png
email: seth.todd@outlook.com
copyright_name: Seth Todd
description: > # this means to ignore newlines until "baseurl:"
  Blog of Seth Todd about my experience learning to Code
baseurl: "/blog" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  satodd1967

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
